name          'postsrsd'
version       '0.1.0'
source        'git@github.com:thomasvs/puppet-postsrsd.git'
author        'thomas'
license       'Apache 2.0'
summary       'Deploy postsrsd, Postfix Sender Rewriting Scheme daemon'
description   ''
project_page  ''

dependency 'puppetlabs/stdlib'
